version: "3.9"
services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - FLASK_APP=app/main.py

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    container_name: mongo

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    container_name: redis
